export const STATE_KEY = 'app';

export const CLEAR_ERROR = `${STATE_KEY}/CLEAR_ERROR`;
export const SET_ERROR = `${STATE_KEY}/SET_ERROR`;

export const BOOTSTRAP = `${STATE_KEY}/BOOTSTRAP`;

export const LOGIN_REQUESTED = `${STATE_KEY}/LOGIN_REQUESTED`;
export const LOGIN_SUCCEEDED = `${STATE_KEY}/LOGIN_SUCCEEDED`;
export const LOGIN_FAILED = `${STATE_KEY}/LOGIN_FAILED`;
export const LOGIN_CANCELLED = `${STATE_KEY}/LOGIN_CANCELLED`;

export const LOGOUT_REQUESTED = `${STATE_KEY}/LOGOUT_REQUESTED`;
export const LOGOUT_SUCCEEDED = `${STATE_KEY}/LOGOUT_SUCCEEDED`;
export const LOGOUT_FAILED = `${STATE_KEY}/LOGOUT_FAILED`;
export const LOGOUT_CANCELLED = `${STATE_KEY}/LOGOUT_CANCELLED`;

export const SIGNIN_REQUESTED = `${STATE_KEY}/SIGNIN_REQUESTED`;
export const SIGNIN_SUCCEEDED = `${STATE_KEY}/SIGNIN_SUCCEEDED`;
export const SIGNIN_FAILED = `${STATE_KEY}/SIGNIN_FAILED`;
export const SIGNIN_CANCELLED = `${STATE_KEY}/SIGNIN_CANCELLED`;
