export const STATE_KEY = 'app';

export const CLEAR_ERROR = `${STATE_KEY}/CLEAR_ERROR`;
export const SET_ERROR = `${STATE_KEY}/SET_ERROR`;

export const LOGIN_REQUESTED = `${STATE_KEY}/LOGIN_REQUESTED`;
export const LOGIN_SUCCEEDED = `${STATE_KEY}/LOGIN_SUCCEEDED`;
export const LOGIN_FAILED = `${STATE_KEY}/LOGIN_FAILED`;
export const LOGIN_CANCELLED = `${STATE_KEY}/LOGIN_CANCELLED`;
