export const STATE_KEY = 'charts';

export const CLEAR_ERROR = `${STATE_KEY}/CLEAR_ERROR`;
export const SET_ERROR = `${STATE_KEY}/SET_ERROR`;

export const LOAD_DATA_REQUESTED = `${STATE_KEY}/LOAD_DATA_REQUESTED`;
export const LOAD_DATA_SUCCEEDED = `${STATE_KEY}/LOAD_DATA_SUCCEEDED`;
export const LOAD_DATA_FAILED = `${STATE_KEY}/LOAD_DATA_FAILED`;
export const LOAD_DATA_CANCELLED = `${STATE_KEY}/LOAD_DATA_CANCELLED`;
